pipeline:

  build:
    image: gradle:5.5.1-jdk8
    environment:
    commands:
      - gradle build
  publish:
    image: plugins/github-release
    files:
      - src/*
    checksum:
      - sha256
    secrets: [github_token]
#    image: plugins/github-release
#    secrets: [github_token]
#    settings:
#      api_key:
#        from_secret: github_token
#      files: runtime.jar
#      checksum:
#        - sha256
    when:
      event: tag