pipeline:

  build:
    image: gradle:5.5.1-jdk8
    environment:
    commands:
      - gradle jar distZip
  publish:
    image: plugins/github-release
    files:
      - build/distributions/*
    checksum:
      - sha256
    secrets: [github_token]
    when:
      event: tag