pipeline:

  build:
    image: gradle:5.5.1-jdk8
    environment:
    commands:
      - gradle build
  publish:
    image: plugins/github-release
    secrets: [github_token]
    settings:
      api_key:
        from_secret: github_token
      files:
        - libs/*
      checksum:
        - md5
    when:
      event: tag