pipeline:
  publish:
    image: plugins/github-release
    secrets: [github_token]
    settings:
      api_key:
        from_secret: github_token
      files:
        - libs/*
      checksum:
        - md5
    when:
      event: tag