pipeline:
  publish:
    image: plugins/github-release
    secrets: [ github_api_key]
    settings:
      api_key: $${GITHUB_API_KEY}
      files:
        - libs/*
      checksum:
        - md5
    when:
      event: tag